# Generated by Django 3.2.13 on 2022-05-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passengerorders',
            fields=[
                ('cold', models.CharField(default='Cold drink', max_length=100, null=True)),
                ('hot', models.CharField(default='Hot drinks', max_length=100, null=True)),
                ('chair', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('food', models.CharField(default='Food', max_length=100, null=True)),
                ('other', models.CharField(default='nothing', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Passengerorders',
            },
        ),
        migrations.CreateModel(
            name='passengers',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fn', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=14)),
                ('gender', models.CharField(default='male', max_length=50)),
                ('age', models.DateField(default='01/01/2004')),
                ('password1', models.CharField(max_length=20, null=True)),
                ('password2', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(default='country', max_length=100)),
            ],
            options={
                'db_table': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('name', models.CharField(default='name', max_length=20, null=True)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rating', models.CharField(default='0', max_length=3)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
